export const inappropriateWords = new Set([
  // Common profanity - add your own list
  "fuck",
  "shit",
  "ass",
  "bitch",
  "damn",
  "crap",
  "dick",
  "cock",
  "pussy",
  "whore",
  "bastard",
  "slut",
  "cunt",
  "piss",
  "retard",
  "faggot",
  "dyke",
  // Racial/ethnic slurs
  "nigger",
  "spic",
  "kike",
  "chink",
  "wetback",
  "gook",
  // Spam patterns
  "viagra",
  "cialis",
  "casino",
  "lottery",
  "winner",
  "prize",
  "pharmacy",
  "medication",
  "discount",
  "free money",
  "make money fast",
  "get rich",
  "investment opportunity",
  "nigerian prince",
  "wire transfer",
  "bank account",
  "credit card",
  "social security",
  "password",
  "bitcoin",
  "crypto",
  "forex",
  "binary options",
  "pyramid scheme",
  "mlm",
  "multi-level marketing",
  "work from home",
  "earn money online",
  "guaranteed returns",
  "limited time offer",
  "act now",
  "congratulations you won",
  "unclaimed funds",
  "inheritance",
  "offshore account",
  "western union",
  "moneygram",
  "paypal",
  // Script-related
  "script",
  "<script>",
  "</script>",
  "javascript:",
  "data:",
  "vbscript:",
  "jscript:",
  "livescript:",
  "ecmascript:",
  "function(",
  "eval(",
  "alert(",
  "document.",
  "window.",
  "setTimeout(",
  "setInterval(",
  "fetch(",
  "xhr.",
  "ajax",
  "jquery",
  "prototype",
  "angular",
  "react",
  "vue",
  // Event handlers
  "onload",
  "onerror",
  "onclick",
  "onmouseover",
  "onmouseout",
  "onmousedown",
  "onmouseup",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "onsubmit",
  "onreset",
  "onselect",
  "onchange",
  "onfocus",
  "onblur",
  "ondblclick",
  "oncontextmenu",
  "ondrag",
  "ondrop",
  "onscroll",
  "onwheel",
  "ontouchstart",
  "ontouchmove",
  "ontouchend",
  "onanimationstart",
  "onanimationend",
  "onanimationiteration",
  "ontransitionend",
  "onabort",
  "oncanplay",
  "oncanplaythrough",
  "ondurationchange",
  "onemptied",
  "onended",
  "onloadeddata",
  "onloadedmetadata",
  "onloadstart",
  "onpause",
  "onplay",
  "onplaying",
  "onprogress",
  "onratechange",
  "onseeked",
  "onseeking",
  "onstalled",
  "onsuspend",
  "ontimeupdate",
  "onvolumechange",
  "onwaiting",
  "oncopy",
  "oncut",
  "onpaste",
  "onbeforeprint",
  "onafterprint",
]);

export const dangerousPatterns = [
  /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
  /javascript:/gi,
  /data:/gi,
  /vbscript:/gi,
  /on\w+\s*=/gi,
  /<iframe/gi,
  /<img[^>]+src\s*=\s*["']?data:/gi,
  /eval\s*\(/gi,
  /expression\s*\(/gi,
  /url\s*\(/gi,
  /base64/gi,
  /alert\s*\(/gi,
  /confirm\s*\(/gi,
  /prompt\s*\(/gi,
  /\[\s*constructor\s*\]/gi,
  /\{\s*constructor\s*\}/gi,
  /__proto__/gi,
  /prototype/gi,
  /<object/gi,
  /<embed/gi,
  /<applet/gi,
  /<form/gi,
  /<meta/gi,
  /<link/gi,
  /<style/gi,
  /document\./gi,
  /window\./gi,
  /\bFunction\(/gi,
  /setTimeout\s*\(/gi,
  /setInterval\s*\(/gi,
  /new\s+Function/gi,
  /debugger/gi,
  /fetch\s*\(/gi,
  /XMLHttpRequest/gi,
  /\$\s*\(/gi, // jQuery
];
